# NumPy

Pythonでベクトルや行列といった配列の計算を効率よく行うには、NumPyライブラリを使うと便利である（[副教材5-3](https://utokyo-ipp.github.io/5/5-3.html)も参照）。標準ライブラリではないので以下のようにインポートして使う。

In [1]:
import numpy as np

as 以降はプログラム内で定義された略称（毎回numpyと書かなくてよくなる）なのでなんでもよいが、普通は np を使うのでそうしよう。

numpy で配列を作るには np.array() 関数を用いる。例えば

In [2]:
a = np.array([1, 2, 3, 4, 5])

とするとリスト [1,2,3,4,5] から numpyの配列（numpy.ndarray）が作れる。

In [3]:
a

array([1, 2, 3, 4, 5])

リストと異なり、array()がついていることに注意。numpy.ndarray として定義するといろんな演算が簡単にできて便利である。例えば

In [4]:
a**2

array([ 1,  4,  9, 16, 25])

は a の全要素を2乗した配列を与える。同様に、足し算

In [5]:
a+1

array([2, 3, 4, 5, 6])

や掛け算

In [6]:
a*2

array([ 2,  4,  6,  8, 10])

のような計算も全要素に対して行われる。2つのnumpy.ndarrayに対しても同様な計算ができる。例えば

In [7]:
b = np.array([-1, -2, -3, -4, -5])

に対して

In [8]:
a + b

array([0, 0, 0, 0, 0])

In [9]:
a * b

array([ -1,  -4,  -9, -16, -25])

は**要素ごとの**和や積を与える。ちなみに上の b は a の各要素を -1 倍したものなので

In [10]:
-a

array([-1, -2, -3, -4, -5])

と書いても同じものが定義できる。これらの操作はリスト（[副教材2-2](https://utokyo-ipp.github.io/2/2-2.html)参照）ではそのままはできない。リストにfor文（[副教材3-2](https://utokyo-ipp.github.io/3/3-2.html)）を適用すればできないことはないが、numpy.ndarray を使った方が速いしコードも短くて済む。

真理値の配列も作れる。例えば

In [11]:
a > 0

array([ True,  True,  True,  True,  True])

はaの各要素が全部正なので全部がTrueの配列になる。

## numpyの関数

numpy には様々な関数が用意されている。例えば上の　a = np.array([1, 2, 3, 4, 5])　は次のようにしても作れる。

In [12]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

arangeというのが関数の名前である。最初の1は含まれるが、6は含まれないことに注意する。Pythonではいつもそういうルールになっている。

簡単な演算を行う関数もnumpyに入っている。例えば

In [13]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

とすると各要素の正の平方根が計算できる。他にも例えば

In [14]:
np.sum(a)

15

とすると配列の全要素の和が得られる。これを使うと、aの要素の平均（mean）は

In [15]:
a_mean = np.sum(a) / len(a)

In [16]:
a_mean

3.0

となる。len(a)はaの要素数（今の場合は5）を返す関数である。実は平均のようなよく使う演算であれば関数が用意されており、

In [17]:
np.mean(a)

3.0

とすれば上のようにしなくても一発で計算できる。平均以外の統計量（中央値や標準偏差など）についても大体関数が用意されている。

上の例のように、関数に入力する値は**関数名の後に丸括弧()をつけてその中に入れる**。一方で、配列の要素を指定する場合は角括弧[]を使うので区別に注意する。例えば、aという配列の0番目（最初）の要素はa[0]と書くと得られる。

In [18]:
a[0]

1

## スライス

がうまく使えるとできることが増える。

In [19]:
a

array([1, 2, 3, 4, 5])

に対して、

In [20]:
a[1:3]

array([2, 3])

とすると、aの1番目以降、3番目より前（上のnp.arange関数の場合と同様3番目は入らない）の要素が取り出せる。最初は0番目と数えるのがPythonのルールである。これ以外に真理値の配列も使える。例えばさっきの

In [21]:
a

array([1, 2, 3, 4, 5])

に対して、3より大きい要素だけ取り出したいとする。そのためには

In [22]:
a > 3

array([False, False, False,  True,  True])

という配列を使って

In [23]:
a[a > 3]

array([4, 5])

とすればよい。もう少し複雑な例として、aと同じ長さの配列cを

In [24]:
c = np.array([1, 0, 0, 1, 0])

で定義し、cが1のところだけ（つまり0番目と3番目）で<u>aの要素について</u>和をとってみる。そのためには

In [25]:
np.sum(a[c==1])

5

などとすればよい。